version: '3.7'

services:
  api:
    container_name: api
    build: 
      context: .
      target: development
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
    command: yarn start:dev
  db:
    container_name: rc-db
    image: 'postgres:12'
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - ./database/pgdata/:/var/lib/postgresql/data

    